### PR TITLE
Issue/location provider

### PR DESCRIPTION
**Pull request by dghalbr**
Had to do a few things that I thought was odd to get this to work on both the node server and in netbeans, but it's working.

### CODE REVIEW

**Comment by neighbor983** [comment]
on the node server i cannot go to the first page i select but i cannot go to another after that.

**Comment by dghalbr** [comment]
I sometimes have to click home before each link. I think we are going to have to preload our html or something.

**Comment by dghalbr** [comment]
Ok, I added templateCache and now this works on Node. I'm not sure if this is how we want to do this forever, but I like it right now.

**Comment by neighbor983** [comment]
Works. I went ahead and added the code to my branch.

**Pull request merged**
