### PR TITLE
Added templateCaching to Gulp tasks.

### PR DESCRIPTION
**Pull request by dghalbr**
Not sure if I was supposed to refactor the entire file for coding standards or not? Also, are gulp tasks something we want to try and write tests for?

### CODE REVIEW

**Comment by neighbor983** [comment]
It is not caching .html files. Because the relative path is off the folder you are putting the templateCache.js in at the public folder were the rest of the .html files are in the public/app file. We can talk about it tomorrow.

**Comment by th3ALPHAnerd** [comment]
I wouldn't worry too much about coding standards, until we come up with something.

**Comment by th3ALPHAnerd** [comment]
I don't know enough about this gulp stuff. I think Kent should approve this request.

**Comment by dghalbr** [comment]
Kent, I see where you told it to not look at some of the other folders in Public. Was including those causing it not to work? Because you said the relative path is off, yet your changes left it in the same location. The only other changes I see are where you added IIFE and changed some syntax in the 'build'? Also, when I ran gulp build on a new machine, it failed because gulp-angular-templatecache wasn't available, but I used --save-dev when I installed it. Shouldn't the gulp build go and download that for the developer?

**Comment by neighbor983** [comment]
Including the asset folder would be a waste because we don't store any of
the html of the application there currently all but one is in the
public/app folder. The templateCaching.js will end up in the app.min.js
which is in the /dist folder that is why you have to start at the public/
level and then go and get all of the html to be templatedCache.

The IIFE piece is not a big deal. We were doing it everywhere else, thought
we would do it there also. I changed the ordering in the build to make sure
the templateCaching would happen before the scripts are concated and
minified.

On the fail make sure you do npm install because npm is handling the all
the dev dependencies in the package.json other then that I am not sure.

**Pull request merged**
